import os
import google.generativeai as genai
from fastapi import FastAPI, HTTPException
from pydantic import BaseModel
from dotenv import load_dotenv
from fastapi.middleware.cors import CORSMiddleware

# Load environment variables from .env file
load_dotenv()

# Configure Gemini AI
GEMINI_API_KEY = os.getenv("GEMINI_API_KEY")
if not GEMINI_API_KEY:
    raise ValueError("⚠️ GEMINI_API_KEY not found in .env file")

genai.configure(api_key=GEMINI_API_KEY)

# Initialize FastAPI
app = FastAPI(
    title="IntelliPrompt API",
    description="AI-powered prompt enhancement & code humanization",
    version="1.0.0"
)

# CORS Middleware (for React Native/Expo connection)
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],  # Production me specific domain daalna
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

# Request Model
class UserRequest(BaseModel):
    input_text: str
    mode: str  # "prompt_enhance" or "code_humanize"

# Helper: AI Response Generator
def get_ai_response(user_input: str, mode: str) -> str:
    try:
        model = genai.GenerativeModel("gemini-pro")
        
        if mode == "prompt_enhance":
            system_prompt = """
            You are an expert Prompt Engineer.
            Task: Convert the user's simple input into a highly structured, professional prompt for LLMs.
            Rules:
            - Add clear Role, Task, Context, Constraints, and Output Format
            - Make it detailed but concise
            - Output ONLY the enhanced prompt, no extra text
            """
        elif mode == "code_humanize":
            system_prompt = """
            You are a Senior Software Developer.
            Task: Rewrite the provided code to look natural, human-written, and well-documented.
            Rules:
            - Improve variable/function names if needed
            - Add meaningful comments
            - Follow clean code practices
            - Output ONLY the improved code block, no explanations
            """
        else:
            return "❌ Invalid mode. Use 'prompt_enhance' or 'code_humanize'."
        
        # Combine system prompt + user input
        full_prompt = f"{system_prompt}\n\n👤 User Input:\n{user_input}"
        
        # Generate response
        response = model.generate_content(full_prompt)
        return response.text.strip()
        
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"🤖 AI Error: {str(e)}")

# API Endpoint: Generate
@app.post("/generate")
async def generate_content(request: UserRequest):
    if not request.input_text or not request.input_text.strip():
        raise HTTPException(status_code=400, detail="⚠️ Input cannot be empty")
    
    # Get AI response
    ai_output = get_ai_response(request.input_text.strip(), request.mode)
    
    return {
        "status": "success",
        "mode": request.mode,
        "original_input": request.input_text,
        "enhanced_output": ai_output,
        "timestamp": __import__("datetime").datetime.now().isoformat()
    }

# Health Check Endpoint
@app.get("/")
async def read_root():
    return {
        "message": "✨ IntelliPrompt API is running with Gemini AI 🚀",
        "endpoints": {
            "POST /generate": "Send {input_text, mode} to get AI output",
            "GET /docs": "Open Swagger UI for testing"
        }
    }

# Docs Endpoint (Auto-generated by FastAPI)
# Visit: http://127.0.0.1:8000/docs